# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: cyclic
version: '0.0.0'
github: "v0d1ch/cyclic"
license: MIT
author: "Sasa Bogicevic"
maintainer: "Sasa Bogicevic"
# synopsis: A new Haskeleton package.
# description: cyclic is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  cyclic:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - cyclic
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  cyclic-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - cyclic
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  cyclic-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - cyclic
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
