name: cyclic
version: '0.0.1'
github: "v0d1ch/cyclic"
license: MIT
author: "Sasa Bogicevic"
maintainer: "Sasa Bogicevic"
synopsis: A class providing cyclic behaviour for Sum types
description: Cyclic class defines cyclic behaviour
             providing ffw and rev functions

extra-source-files:
- package.yaml
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

tests:
  cyclic-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - cyclic
    - hedgehog
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
